/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-06-26 16:27:34 UTC)
 * on 2013-06-26 at 22:58:26 UTC 
 * Modify at your own risk.
 */

package de.roman.meter.meterendpoint;

/**
 * Service definition for Meterendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link MeterendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Meterendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.15.0-rc of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://metertracker.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "meterendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Meterendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Meterendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getMeter".
   *
   * This request holds the parameters needed by the the meterendpoint server.  After setting any
   * optional parameters, call the {@link GetMeter#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetMeter getMeter(java.lang.Long id) throws java.io.IOException {
    GetMeter result = new GetMeter(id);
    initialize(result);
    return result;
  }

  public class GetMeter extends MeterendpointRequest<de.roman.meter.meterendpoint.model.Meter> {

    private static final String REST_PATH = "meter/{id}";

    /**
     * Create a request for the method "getMeter".
     *
     * This request holds the parameters needed by the the meterendpoint server.  After setting any
     * optional parameters, call the {@link GetMeter#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetMeter#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetMeter(java.lang.Long id) {
      super(Meterendpoint.this, "GET", REST_PATH, null, de.roman.meter.meterendpoint.model.Meter.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetMeter setAlt(java.lang.String alt) {
      return (GetMeter) super.setAlt(alt);
    }

    @Override
    public GetMeter setFields(java.lang.String fields) {
      return (GetMeter) super.setFields(fields);
    }

    @Override
    public GetMeter setKey(java.lang.String key) {
      return (GetMeter) super.setKey(key);
    }

    @Override
    public GetMeter setOauthToken(java.lang.String oauthToken) {
      return (GetMeter) super.setOauthToken(oauthToken);
    }

    @Override
    public GetMeter setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetMeter) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetMeter setQuotaUser(java.lang.String quotaUser) {
      return (GetMeter) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetMeter setUserIp(java.lang.String userIp) {
      return (GetMeter) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetMeter setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetMeter set(String parameterName, Object value) {
      return (GetMeter) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertMeter".
   *
   * This request holds the parameters needed by the the meterendpoint server.  After setting any
   * optional parameters, call the {@link InsertMeter#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link de.roman.meter.meterendpoint.model.Meter}
   * @return the request
   */
  public InsertMeter insertMeter(de.roman.meter.meterendpoint.model.Meter content) throws java.io.IOException {
    InsertMeter result = new InsertMeter(content);
    initialize(result);
    return result;
  }

  public class InsertMeter extends MeterendpointRequest<de.roman.meter.meterendpoint.model.Meter> {

    private static final String REST_PATH = "meter";

    /**
     * Create a request for the method "insertMeter".
     *
     * This request holds the parameters needed by the the meterendpoint server.  After setting any
     * optional parameters, call the {@link InsertMeter#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertMeter#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link de.roman.meter.meterendpoint.model.Meter}
     * @since 1.13
     */
    protected InsertMeter(de.roman.meter.meterendpoint.model.Meter content) {
      super(Meterendpoint.this, "POST", REST_PATH, content, de.roman.meter.meterendpoint.model.Meter.class);
    }

    @Override
    public InsertMeter setAlt(java.lang.String alt) {
      return (InsertMeter) super.setAlt(alt);
    }

    @Override
    public InsertMeter setFields(java.lang.String fields) {
      return (InsertMeter) super.setFields(fields);
    }

    @Override
    public InsertMeter setKey(java.lang.String key) {
      return (InsertMeter) super.setKey(key);
    }

    @Override
    public InsertMeter setOauthToken(java.lang.String oauthToken) {
      return (InsertMeter) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertMeter setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertMeter) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertMeter setQuotaUser(java.lang.String quotaUser) {
      return (InsertMeter) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertMeter setUserIp(java.lang.String userIp) {
      return (InsertMeter) super.setUserIp(userIp);
    }

    @Override
    public InsertMeter set(String parameterName, Object value) {
      return (InsertMeter) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listMeter".
   *
   * This request holds the parameters needed by the the meterendpoint server.  After setting any
   * optional parameters, call the {@link ListMeter#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListMeter listMeter() throws java.io.IOException {
    ListMeter result = new ListMeter();
    initialize(result);
    return result;
  }

  public class ListMeter extends MeterendpointRequest<de.roman.meter.meterendpoint.model.CollectionResponseMeter> {

    private static final String REST_PATH = "meter";

    /**
     * Create a request for the method "listMeter".
     *
     * This request holds the parameters needed by the the meterendpoint server.  After setting any
     * optional parameters, call the {@link ListMeter#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListMeter#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListMeter() {
      super(Meterendpoint.this, "GET", REST_PATH, null, de.roman.meter.meterendpoint.model.CollectionResponseMeter.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListMeter setAlt(java.lang.String alt) {
      return (ListMeter) super.setAlt(alt);
    }

    @Override
    public ListMeter setFields(java.lang.String fields) {
      return (ListMeter) super.setFields(fields);
    }

    @Override
    public ListMeter setKey(java.lang.String key) {
      return (ListMeter) super.setKey(key);
    }

    @Override
    public ListMeter setOauthToken(java.lang.String oauthToken) {
      return (ListMeter) super.setOauthToken(oauthToken);
    }

    @Override
    public ListMeter setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListMeter) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListMeter setQuotaUser(java.lang.String quotaUser) {
      return (ListMeter) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListMeter setUserIp(java.lang.String userIp) {
      return (ListMeter) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListMeter setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListMeter setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListMeter set(String parameterName, Object value) {
      return (ListMeter) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeMeter".
   *
   * This request holds the parameters needed by the the meterendpoint server.  After setting any
   * optional parameters, call the {@link RemoveMeter#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveMeter removeMeter(java.lang.Long id) throws java.io.IOException {
    RemoveMeter result = new RemoveMeter(id);
    initialize(result);
    return result;
  }

  public class RemoveMeter extends MeterendpointRequest<de.roman.meter.meterendpoint.model.Meter> {

    private static final String REST_PATH = "meter/{id}";

    /**
     * Create a request for the method "removeMeter".
     *
     * This request holds the parameters needed by the the meterendpoint server.  After setting any
     * optional parameters, call the {@link RemoveMeter#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveMeter#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveMeter(java.lang.Long id) {
      super(Meterendpoint.this, "DELETE", REST_PATH, null, de.roman.meter.meterendpoint.model.Meter.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveMeter setAlt(java.lang.String alt) {
      return (RemoveMeter) super.setAlt(alt);
    }

    @Override
    public RemoveMeter setFields(java.lang.String fields) {
      return (RemoveMeter) super.setFields(fields);
    }

    @Override
    public RemoveMeter setKey(java.lang.String key) {
      return (RemoveMeter) super.setKey(key);
    }

    @Override
    public RemoveMeter setOauthToken(java.lang.String oauthToken) {
      return (RemoveMeter) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveMeter setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveMeter) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveMeter setQuotaUser(java.lang.String quotaUser) {
      return (RemoveMeter) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveMeter setUserIp(java.lang.String userIp) {
      return (RemoveMeter) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveMeter setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveMeter set(String parameterName, Object value) {
      return (RemoveMeter) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateMeter".
   *
   * This request holds the parameters needed by the the meterendpoint server.  After setting any
   * optional parameters, call the {@link UpdateMeter#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link de.roman.meter.meterendpoint.model.Meter}
   * @return the request
   */
  public UpdateMeter updateMeter(de.roman.meter.meterendpoint.model.Meter content) throws java.io.IOException {
    UpdateMeter result = new UpdateMeter(content);
    initialize(result);
    return result;
  }

  public class UpdateMeter extends MeterendpointRequest<de.roman.meter.meterendpoint.model.Meter> {

    private static final String REST_PATH = "meter";

    /**
     * Create a request for the method "updateMeter".
     *
     * This request holds the parameters needed by the the meterendpoint server.  After setting any
     * optional parameters, call the {@link UpdateMeter#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateMeter#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link de.roman.meter.meterendpoint.model.Meter}
     * @since 1.13
     */
    protected UpdateMeter(de.roman.meter.meterendpoint.model.Meter content) {
      super(Meterendpoint.this, "PUT", REST_PATH, content, de.roman.meter.meterendpoint.model.Meter.class);
    }

    @Override
    public UpdateMeter setAlt(java.lang.String alt) {
      return (UpdateMeter) super.setAlt(alt);
    }

    @Override
    public UpdateMeter setFields(java.lang.String fields) {
      return (UpdateMeter) super.setFields(fields);
    }

    @Override
    public UpdateMeter setKey(java.lang.String key) {
      return (UpdateMeter) super.setKey(key);
    }

    @Override
    public UpdateMeter setOauthToken(java.lang.String oauthToken) {
      return (UpdateMeter) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateMeter setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateMeter) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateMeter setQuotaUser(java.lang.String quotaUser) {
      return (UpdateMeter) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateMeter setUserIp(java.lang.String userIp) {
      return (UpdateMeter) super.setUserIp(userIp);
    }

    @Override
    public UpdateMeter set(String parameterName, Object value) {
      return (UpdateMeter) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Meterendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Meterendpoint}. */
    @Override
    public Meterendpoint build() {
      return new Meterendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link MeterendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setMeterendpointRequestInitializer(
        MeterendpointRequestInitializer meterendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(meterendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
