/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-06-26 16:27:34 UTC)
 * on 2013-07-18 at 15:42:35 UTC 
 * Modify at your own risk.
 */

package de.roman.meter.metercountendpoint;

/**
 * Service definition for Metercountendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link MetercountendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Metercountendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.15.0-rc of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://metertracker.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "metercountendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Metercountendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Metercountendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getMeterCount".
   *
   * This request holds the parameters needed by the the metercountendpoint server.  After setting any
   * optional parameters, call the {@link GetMeterCount#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetMeterCount getMeterCount(java.lang.Long id) throws java.io.IOException {
    GetMeterCount result = new GetMeterCount(id);
    initialize(result);
    return result;
  }

  public class GetMeterCount extends MetercountendpointRequest<de.roman.meter.metercountendpoint.model.MeterCount> {

    private static final String REST_PATH = "metercount/{id}";

    /**
     * Create a request for the method "getMeterCount".
     *
     * This request holds the parameters needed by the the metercountendpoint server.  After setting
     * any optional parameters, call the {@link GetMeterCount#execute()} method to invoke the remote
     * operation. <p> {@link GetMeterCount#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetMeterCount(java.lang.Long id) {
      super(Metercountendpoint.this, "GET", REST_PATH, null, de.roman.meter.metercountendpoint.model.MeterCount.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetMeterCount setAlt(java.lang.String alt) {
      return (GetMeterCount) super.setAlt(alt);
    }

    @Override
    public GetMeterCount setFields(java.lang.String fields) {
      return (GetMeterCount) super.setFields(fields);
    }

    @Override
    public GetMeterCount setKey(java.lang.String key) {
      return (GetMeterCount) super.setKey(key);
    }

    @Override
    public GetMeterCount setOauthToken(java.lang.String oauthToken) {
      return (GetMeterCount) super.setOauthToken(oauthToken);
    }

    @Override
    public GetMeterCount setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetMeterCount) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetMeterCount setQuotaUser(java.lang.String quotaUser) {
      return (GetMeterCount) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetMeterCount setUserIp(java.lang.String userIp) {
      return (GetMeterCount) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetMeterCount setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetMeterCount set(String parameterName, Object value) {
      return (GetMeterCount) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertMeterCount".
   *
   * This request holds the parameters needed by the the metercountendpoint server.  After setting any
   * optional parameters, call the {@link InsertMeterCount#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link de.roman.meter.metercountendpoint.model.MeterCount}
   * @return the request
   */
  public InsertMeterCount insertMeterCount(de.roman.meter.metercountendpoint.model.MeterCount content) throws java.io.IOException {
    InsertMeterCount result = new InsertMeterCount(content);
    initialize(result);
    return result;
  }

  public class InsertMeterCount extends MetercountendpointRequest<de.roman.meter.metercountendpoint.model.MeterCount> {

    private static final String REST_PATH = "metercount";

    /**
     * Create a request for the method "insertMeterCount".
     *
     * This request holds the parameters needed by the the metercountendpoint server.  After setting
     * any optional parameters, call the {@link InsertMeterCount#execute()} method to invoke the
     * remote operation. <p> {@link InsertMeterCount#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link de.roman.meter.metercountendpoint.model.MeterCount}
     * @since 1.13
     */
    protected InsertMeterCount(de.roman.meter.metercountendpoint.model.MeterCount content) {
      super(Metercountendpoint.this, "POST", REST_PATH, content, de.roman.meter.metercountendpoint.model.MeterCount.class);
    }

    @Override
    public InsertMeterCount setAlt(java.lang.String alt) {
      return (InsertMeterCount) super.setAlt(alt);
    }

    @Override
    public InsertMeterCount setFields(java.lang.String fields) {
      return (InsertMeterCount) super.setFields(fields);
    }

    @Override
    public InsertMeterCount setKey(java.lang.String key) {
      return (InsertMeterCount) super.setKey(key);
    }

    @Override
    public InsertMeterCount setOauthToken(java.lang.String oauthToken) {
      return (InsertMeterCount) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertMeterCount setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertMeterCount) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertMeterCount setQuotaUser(java.lang.String quotaUser) {
      return (InsertMeterCount) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertMeterCount setUserIp(java.lang.String userIp) {
      return (InsertMeterCount) super.setUserIp(userIp);
    }

    @Override
    public InsertMeterCount set(String parameterName, Object value) {
      return (InsertMeterCount) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listMeterCount".
   *
   * This request holds the parameters needed by the the metercountendpoint server.  After setting any
   * optional parameters, call the {@link ListMeterCount#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListMeterCount listMeterCount() throws java.io.IOException {
    ListMeterCount result = new ListMeterCount();
    initialize(result);
    return result;
  }

  public class ListMeterCount extends MetercountendpointRequest<de.roman.meter.metercountendpoint.model.CollectionResponseMeterCount> {

    private static final String REST_PATH = "metercount";

    /**
     * Create a request for the method "listMeterCount".
     *
     * This request holds the parameters needed by the the metercountendpoint server.  After setting
     * any optional parameters, call the {@link ListMeterCount#execute()} method to invoke the remote
     * operation. <p> {@link ListMeterCount#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListMeterCount() {
      super(Metercountendpoint.this, "GET", REST_PATH, null, de.roman.meter.metercountendpoint.model.CollectionResponseMeterCount.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListMeterCount setAlt(java.lang.String alt) {
      return (ListMeterCount) super.setAlt(alt);
    }

    @Override
    public ListMeterCount setFields(java.lang.String fields) {
      return (ListMeterCount) super.setFields(fields);
    }

    @Override
    public ListMeterCount setKey(java.lang.String key) {
      return (ListMeterCount) super.setKey(key);
    }

    @Override
    public ListMeterCount setOauthToken(java.lang.String oauthToken) {
      return (ListMeterCount) super.setOauthToken(oauthToken);
    }

    @Override
    public ListMeterCount setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListMeterCount) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListMeterCount setQuotaUser(java.lang.String quotaUser) {
      return (ListMeterCount) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListMeterCount setUserIp(java.lang.String userIp) {
      return (ListMeterCount) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListMeterCount setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListMeterCount setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListMeterCount set(String parameterName, Object value) {
      return (ListMeterCount) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeMeterCount".
   *
   * This request holds the parameters needed by the the metercountendpoint server.  After setting any
   * optional parameters, call the {@link RemoveMeterCount#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveMeterCount removeMeterCount(java.lang.Long id) throws java.io.IOException {
    RemoveMeterCount result = new RemoveMeterCount(id);
    initialize(result);
    return result;
  }

  public class RemoveMeterCount extends MetercountendpointRequest<de.roman.meter.metercountendpoint.model.MeterCount> {

    private static final String REST_PATH = "metercount/{id}";

    /**
     * Create a request for the method "removeMeterCount".
     *
     * This request holds the parameters needed by the the metercountendpoint server.  After setting
     * any optional parameters, call the {@link RemoveMeterCount#execute()} method to invoke the
     * remote operation. <p> {@link RemoveMeterCount#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveMeterCount(java.lang.Long id) {
      super(Metercountendpoint.this, "DELETE", REST_PATH, null, de.roman.meter.metercountendpoint.model.MeterCount.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveMeterCount setAlt(java.lang.String alt) {
      return (RemoveMeterCount) super.setAlt(alt);
    }

    @Override
    public RemoveMeterCount setFields(java.lang.String fields) {
      return (RemoveMeterCount) super.setFields(fields);
    }

    @Override
    public RemoveMeterCount setKey(java.lang.String key) {
      return (RemoveMeterCount) super.setKey(key);
    }

    @Override
    public RemoveMeterCount setOauthToken(java.lang.String oauthToken) {
      return (RemoveMeterCount) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveMeterCount setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveMeterCount) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveMeterCount setQuotaUser(java.lang.String quotaUser) {
      return (RemoveMeterCount) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveMeterCount setUserIp(java.lang.String userIp) {
      return (RemoveMeterCount) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveMeterCount setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveMeterCount set(String parameterName, Object value) {
      return (RemoveMeterCount) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateMeterCount".
   *
   * This request holds the parameters needed by the the metercountendpoint server.  After setting any
   * optional parameters, call the {@link UpdateMeterCount#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link de.roman.meter.metercountendpoint.model.MeterCount}
   * @return the request
   */
  public UpdateMeterCount updateMeterCount(de.roman.meter.metercountendpoint.model.MeterCount content) throws java.io.IOException {
    UpdateMeterCount result = new UpdateMeterCount(content);
    initialize(result);
    return result;
  }

  public class UpdateMeterCount extends MetercountendpointRequest<de.roman.meter.metercountendpoint.model.MeterCount> {

    private static final String REST_PATH = "metercount";

    /**
     * Create a request for the method "updateMeterCount".
     *
     * This request holds the parameters needed by the the metercountendpoint server.  After setting
     * any optional parameters, call the {@link UpdateMeterCount#execute()} method to invoke the
     * remote operation. <p> {@link UpdateMeterCount#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link de.roman.meter.metercountendpoint.model.MeterCount}
     * @since 1.13
     */
    protected UpdateMeterCount(de.roman.meter.metercountendpoint.model.MeterCount content) {
      super(Metercountendpoint.this, "PUT", REST_PATH, content, de.roman.meter.metercountendpoint.model.MeterCount.class);
    }

    @Override
    public UpdateMeterCount setAlt(java.lang.String alt) {
      return (UpdateMeterCount) super.setAlt(alt);
    }

    @Override
    public UpdateMeterCount setFields(java.lang.String fields) {
      return (UpdateMeterCount) super.setFields(fields);
    }

    @Override
    public UpdateMeterCount setKey(java.lang.String key) {
      return (UpdateMeterCount) super.setKey(key);
    }

    @Override
    public UpdateMeterCount setOauthToken(java.lang.String oauthToken) {
      return (UpdateMeterCount) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateMeterCount setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateMeterCount) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateMeterCount setQuotaUser(java.lang.String quotaUser) {
      return (UpdateMeterCount) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateMeterCount setUserIp(java.lang.String userIp) {
      return (UpdateMeterCount) super.setUserIp(userIp);
    }

    @Override
    public UpdateMeterCount set(String parameterName, Object value) {
      return (UpdateMeterCount) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Metercountendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Metercountendpoint}. */
    @Override
    public Metercountendpoint build() {
      return new Metercountendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link MetercountendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setMetercountendpointRequestInitializer(
        MetercountendpointRequestInitializer metercountendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(metercountendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
